### ISSUE TITLE
뷰 로딩 실패시 예외 처리

### ISSUE THREAD

**Issue by kjoonk** [codesquad-member-2020/airbnb-03#75]
- [ ] 디버그와 릴리즈 구분
- [ ] 릴리즈 시 alert 등 형태로 사용자에게 알림 처리

_Originally posted by @kjoonk in https://github.com/codesquad-member-2020/airbnb-03/pull/73/review_comment/create_

**Comment by corykim0829** [comment]
디버그와 릴리즈는 어떻게 구분해야할지 모르겠네요 브랜치로 분류할 것 같은 느낌이 들기는 하네요..
사용자에게 alert와 같은 형태로 알림 처리를 할 필요까지 있을까요?

**Comment by kjoonk** [comment]
디버그 구분은 `#if DEBUG` 형태로 하면 될 것 같아요.
alert 메시지는 "앱을 실행하는 데 문제가 발생했습니다" 하고 종료시키는 걸 생각했는데, 다른 나은 방법이 있을까요?

**Comment by corykim0829** [comment]
음 alert뷰로 처리해도 될 것 같아요! 나중에 시간 되시면 진행해주세요!
